services:

  frontend-demo:
    container_name: frontend-demo
    build:
        context: .
    volumes:
      - .:/code/
    ports:
      - 3000:3000
    networks:
      - frontend-network
networks:
  frontend:
    name: frontend-network

#    docker image tag frontend-frontend-demo yuriichml1/front:1.0
#
#    docker push yuriichml1/front:1.0