apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # Backend API
    - host: {{ .Values.backend.ingress.host | default "api.local.test" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name | default (include "chart.fullname" .) }}-golang-demo-svc
                port:
                  number: {{ .Values.backend.service.port | default 8080 }}