apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: {{ .Values.frontend.deployment.label | default "frontend-demo" }}
  name: {{ include "chart.fullname" . }}-frontend-demo
spec:
  replicas: {{ .Values.frontend.deployment.replicas | default 10 }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.frontend.deployment.label | default "frontend-demo" }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: {{ .Values.frontend.deployment.label | default "frontend-demo" }}
    spec:
      containers:
        - env:
            - name: REACT_APP_BACKEND_URL
              value: {{ .Values.frontend.deployment.backendURL }}
          image: {{ .Values.frontend.deployment.image }}:{{ .Values.frontend.deployment.tag }}
          name: {{ .Values.frontend.deployment.container.name | default "frontend-demo" }}
          ports:
            - containerPort: {{ .Values.frontend.deployment.container.port | default 3001 }}
              protocol: TCP
      restartPolicy: Always