apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: frontend-demo
  name: frontend-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
#      nodePort: 30080
  selector:
    io.kompose.service: frontend-demo
