apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: frontend-demo
  name: frontend-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-demo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: frontend-demo
    spec:
      containers:
        - env:
            - name: REACT_APP_BACKEND_URL
              value: http://13.48.78.189:8080
          image: docker.io/yuriichml1/front:2.0
          name: frontend-demo
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
