global:
  scrape_interval: 5s
scrape_configs:

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8181']
  - job_name: golang-demo
    static_configs:
      - targets: ['golang-demo:8080']