global:
  scrape_interval: 5s
scrape_configs:

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels:
          - __meta_docker_container_label_com_docker_compose_project
          - __meta_docker_container_label_com_docker_compose_service
        separator: ;
        regex: "prometheus-stack;app"
        action: keep
      - source_labels:
          - __meta_docker_network_ip
        target_label: __address__
        action: replace
        replacement: "$1:8000"
      - source_labels:
          - __meta_docker_container_name
        target_label: container_name
        regex: /(.*)
        action: replace
#  - job_name: cadvisor
#    static_configs:
#      - targets: ['cadvisor:8181']