---
name: build-push-deploy-prod
#act --container-architecture linux/amd64 --secret-file my.secrets -W '.github/workflows/build_push_deploy_frontend.yaml' -P ubuntu-22.04=catthehacker/ubuntu:act-latest
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.backend/**'

jobs:
  build-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders

      - name: Log in to Docker Hub and push image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: yuriichml1/front:latest
          context: .
          file: frontend/Dockerfile

#      - name: Build and push image
#        uses: docker/build-push-action@v6
#        env:
#          DOCKER_BUILDKIT: 1
#          SERVICE: ${{ matrix.service }}
#          ECR_REPOSITORY: ${{ matrix.repository }}
#          IMAGE_CACHE_REPO: ${{ matrix.image_cache_repo }}
#        with:
#          context: .
#          file: deployments/docker/Dockerfile
#          push: true
#          target: prod
#          cache-from: type=registry,ref=${{ env.IMAGE_CACHE_REPO }}
#          cache-to: type=registry,ref=${{ env.IMAGE_CACHE_REPO }},mode=max,image-manifest=true,oci-mediatypes=true
#          tags: |
#            968199160813.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.COMMIT_HASH }}

#  deploy:
#    runs-on: [self-hosted, linux, x64, bodyfit-msa, prod]
#    needs:
#      - build-push
#    env:
#      BRANCH: master
#      TAG_FILE_PATH: email/values_prod/global.yaml
#      CONSUMER_FILE_PATH: email/values_prod/email.yaml
#      SERVER_FILE_PATH: email/values_prod/http-server.yaml
#
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          repository: 'amomama/bodyfit-email-charts'
#          ref: ${{ env.BRANCH }}
#          token: ${{ secrets.GH_TOKEN }}
#
#      - uses: actions/download-artifact@v4
#        with:
#          name: commit-hash
#
#      - name: Save commit hash to GITHUB ENV
#        run: |
#          echo "COMMIT_HASH=$(cat commit_hash)" >> $GITHUB_ENV
#
#      - uses: actions/download-artifact@v4
#        with:
#          name: commit-link
#
#      - name: Save commit link to GITHUB ENV
#        run: |
#          echo "COMMIT_LINK=$(cat commit_link)" >> $GITHUB_ENV
#
#      - name: Update charts commit hash
#        run: |
#          sed -i -E "s/([ \t]*tag\: )(.*)/\1\'${{env.COMMIT_HASH}}\'/" ${{ env.CONSUMER_FILE_PATH }}
#          sed -i -E "s/([ \t]*tag\: )(.*)/\1\'${{env.COMMIT_HASH}}\'/" ${{ env.SERVER_FILE_PATH }}
#          sed -i -E "s#([ \t]*link\: )(.*)#\1${{env.COMMIT_LINK}}#" ${{ env.TAG_FILE_PATH }}
#
#      - name: Commit changes
#        uses: EndBug/add-and-commit@v9.1.4
#        with:
#          author_name: GitHub Actions
#          author_email: operations@amomedia.com
#          message: "Updated to commit ${{env.COMMIT_LINK}}"
